import {
  AlertTriangle,
  ArrowRight,
  BarChart,
  Bell,
  Calendar,
  Check,
  ChevronLeft,
  ChevronRight,
  CreditCard,
  Download,
  Edit,
  Eye,
  Facebook,
  FileText,
  Filter,
  Github,
  Grid,
  ImageIcon,
  Key,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  LayoutList,
  LogIn,
  LogOut,
  type LightbulbIcon as LucideProps,
  Mail,
  Menu,
  MoreHorizontal,
  Package,
  Plus,
  Search,
  Settings,
  LoaderPinwheelIcon as Spinner,
  Trash,
  User,
  UserPlus,
  Users,
  X,
} from "lucide-react"

export type IconProps = typeof LucideProps

export const Icons = {
  logo: ImageIcon,
  close: X,
  spinner: Spinner,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  mail: Mail,
  check: Check,
  dashboard: LayoutDashboard,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreHorizontal,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: AlertTriangle,
  users: Users,
  post: FileText,
  page: FileText,
  media: ImageIcon,
  login: LogIn,
  logout: LogOut,
  calendar: Calendar,
  creditCard: CreditCard,
  barChart: BarChart,
  bell: Bell,
  menu: Menu,
  download: Download,
  edit: Edit,
  key: Key,
  package: Package,
  layers: Layers,
  userPlus: UserPlus,
  facebook: Facebook,
  google: Github,
  search: Search,
  filter: Filter,
  eye: Eye,
  trash: Trash,
  plus: Plus,
  layoutGrid: LayoutGrid,
  layoutList: LayoutList,
  grid: Grid,
}
